name: EtherDecompositor
version: ${version}
author: Sapphira Tempest
description: Manage behaviour and regulate plugins of Ether Combination.

main: io.sn.etherdec.EtherCore
depend:
  - Slimefun
  - CommandAPI
  - NBTAPI
  - ItemsAdder
  - Vault
  - PlaceholderAPI
  - EmeraldBank

api-version: 1.20

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.20
  - com.alibaba.fastjson2:fastjson2:2.0.35
