package io.sn.etherdec.modules

import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack
import io.sn.etherdec.EtherCore
import io.sn.etherdec.objects.AbstractModule
import org.bukkit.Material

class Ammo(plug: EtherCore) : AbstractModule(plug) {

    override fun postSetup() {
        AmmoList.ammoNames.zip(AmmoList.ammoIds).forEach {
            registerAmmo(it.first, it.second)
        }
    }

    private fun registerAmmo(name: String, id: String) {
        SlimefunItem(
            plug.group, SlimefunItemStack(
                "ETHERITE_AMMO_${id.uppercase()}", Material.PRISMARINE_SHARD,
                "&f弹药 &7- &e$name&r"
            ), type, nullRecipe
        ).register(plug)
    }

}

object AmmoList {

    val ammoIds = arrayOf(
        "12GINCENDIARYAMMO",
        "SIDEWINDER7AMMO",
        "HESNIPERAMMO",
        "FAMASAMMO",
        "PR3OSCAMMO",
        "PR3AMMO",
        "SPASAMMO",
        "AN94AMMO",
        "MP5AMMO",
        "Z20SIGNETAMMO",
        "M14AMMO",
        "BARRETTEXPLOSIVEAMMO",
        "ROCKETPOD57MMAMMO",
        "BARRETTAMMO",
        "M1887AMMO",
        "M40A3AMMO",
        "12GBUCKSHOTAMMO",
        "SKORPIONAMMO",
        "BIZONAMMO",
        "SIGP226AMMO",
        "FLAREGUNBLUEAMMO",
        "SPLITTERCANNONREFRACTEDAMMO",
        "B4CROSSBOWAMMO",
        "P90AMMO",
        "KCASMARTCARBINEAMMO",
        "SG550AMMO",
        "NTW20AMMO",
        "EMP4AMMO",
        "AMA40MMSPOTLIGHTAMMO",
        "STINGERAMMO",
        "MINIUZIAMMO",
        "M72LAWAMMO",
        "HIGHEXPISTOLAMMO",
        "GAU19AMMO",
        "BARRETTCOMPACTAMMO",
        "R700AMMO",
        "Z10LIGHTRIFLEAMMO",
        "AK47AMMO",
        "TRIPLETAKEAMMO",
        "SEEKERRIFLEAMMO",
        "FNSCARAMMO",
        "FLAREGUNBLACKAMMO",
        "FLAREGUNGREENAMMO",
        "MINIGUNEXPLOSIVEAMMO",
        "WITHERINGAKAMMO",
        "12GBIRDSHOTAMMO",
        "L86AMMO",
        "G3AMMO",
        "ACRAMMO",
        "AUGAMMO",
        "FLAMETHROWERAMMO",
        "GAU24MMHEAMMO",
        "HYDRA70AMMO",
        "MTARAMMO",
        "STARSAMMO",
        "FLAREGUNWHITEAMMO",
        "ASH12AMMO",
        "M1014AMMO",
        "AA12AMMO",
        "12GSLUGAMMO",
        "MINIGUNAMMO",
        "GAU20MMARCAMMO",
        "KRISSVECTORAMMO",
        "R870AMMO",
        "ADAR15AMMO",
        "GAU30MMAMMO",
        "FLAREGUNAMMO",
        "STARSNCI3AMMO",
        "DESERTEAGLEAMMO",
        "MLRS6AMMO",
        "M60E4AMMO",
        "DRAGUNOVAMMO",
        "SHULKERSNIPERAMMO",
        "MWAMMOBAG",
        "AMA40MMAMMO",
        "AT4AMMO",
        "GAU30MMHEAMMO",
        "DEVOTIONX55AMMO",
        "KCASLUGGERAMMO",
        "12GHIGHEXPLOSIVEAMMO",
        "W1200AMMO",
        "M16A4AMMO",
        "M249AMMO",
        "GLOCKAMMO",
        "HONEYBADGERAMMO",
        "RPGAMMO",
        "12GFLECHETTEAMMO",
        "L96AMMO",
        "PREDATOR37MMSRAMMO",
        "GRENADELAUNCHERAMMO",
        "M21AMMO",
        "PAW20AMMO",
        "12GPOISONEDFLECHETTEAMMO",
        "GRENADELAUNCHERINCENDIARYAMMO",
        "GRENADELAUNCHERBOUNCYAMMO",
        "GALILAMMO",
        "RPKAMMO",
        "AU40MMHEAMMO",
        "HCARAMMO",
        "KCASMART50AMMO",
        "APCRRIFLEAMMO",
        "GAU20MMAMMO",
        "W1200INCENDIARYAMMO",
        "USPPOISONAMMO",
        "ROCKETPOD68MMAMMO",
        "SNIPERAMMO",
        "PANZERFAUST3AMMO",
        "MINIGUNAMMOPORTABLE",
        "BASICSALVOAMMO",
        "COLDWARE2AMMO",
        "GRENADELAUNCHERGASAMMO",
        "AU40MMAMMO",
        "RPDAMMO",
        "G36AMMO",
        "Z45SENTINELAMMO",
        "AK74AMMO",
        "ADVANCEDSALVOAMMO",
        "KCASMARTPISTOLAMMO",
        "A91AMMO",
        "SPLITTERCANNONAMMO",
        "PREDATOR37MMAMMO",
        "PREDATOR37MMLRAMMO",
        "SMG100AMMO",
        "GRENADELAUNCHERIMPACTAMMO",
        "VOLTV3AMMO",
        "JURYAMMO",
        "STARSBURNINGRUBBERAMMO",
        "GAU20MMHVLEAMMO",
        "GAU24MMAMMO",
        "KCASLUGGERKINETICAMMO",
        "USPAMMO",
        "COLT45AMMO",
        "M9AMMO",
        "Z16SPLICERRIFLEAMMO",
        "MASTIFF1218AMMO",
        "APPISTOLAMMO",
        "Z15SPLICERAMMO"
    )

    val ammoNames = arrayOf(
        "12G 燃烧弹",
        "SideWinder7 弹夹",
        "手枪子弹 &8(&f9.06mm&8)", // .357 Magnum
        "突击步枪弹夹 &8(&f5.56mm&8)", // FR_5.56, M4A1, AUG
        "PR3OSC ammo",
        "PR3 ammo",
        "SPAS ammo",
        "AN94 ammo",
        "MP5 ammo",
        "Z20SIGNET ammo",
        "M14 ammo",
        "BARRETTEXPLOSIVE ammo",
        "ROCKETPOD57MM ammo",
        "BARRETT ammo",
        "M1887 ammo",
        "M40A3 ammo",
        "12GBUCKSHOT ammo",
        "SKORPION ammo",
        "BIZON ammo",
        "SIGP226 ammo",
        "FLAREGUNBLUE ammo",
        "SPLITTERCANNONREFRACTED ammo",
        "B4CROSSBOW ammo",
        "P90 ammo",
        "KCASMARTCARBINE ammo",
        "SG550 ammo",
        "NTW20 ammo",
        "EMP4 ammo",
        "AMA40MMSPOTLIGHT ammo",
        "STINGER ammo",
        "Uzi 冲锋枪弹夹", // Uzi
        "M72LAW ammo",
        "狙击枪子弹 &8(&f12.7mm&8)", // AX_50
        "GAU19 ammo",
        "BARRETTCOMPACT ammo",
        "R700 ammo",
        "Z10LIGHTRIFLE ammo",
        "突击步枪弹夹 &8(&f7.62mm&8)", // AK_47, FN_FAL
        "TRIPLETAKE ammo",
        "SEEKERRIFLE ammo",
        "FNSCARAMMO",
        "FLAREGUNBLACK ammo",
        "FLAREGUNGREEN ammo",
        "MINIGUNEXPLOSIVE ammo",
        "WITHERINGAK ammo",
        "12GBIRDSHOT ammo",
        "L86 ammo",
        "突击步枪弹夹 &8(&f7.92mm&8)", // STG44
        "ACR ammo",
        "AUG ammo",
        "FLAMETHROWER ammo",
        "GAU24MMHE ammo",
        "HYDRA70 ammo",
        "MTAR ammo",
        "STARS ammo",
        "FLAREGUNWHITE ammo",
        "ASH12 ammo",
        "M1014 ammo",
        "AA12 ammo",
        "12GSLUG ammo",
        "MINIGUN ammo",
        "GAU20MMARC ammo",
        "KRISSVECTORAMMO",
        "R870 ammo",
        "ADAR15 ammo",
        "GAU30MM ammo",
        "FLAREGUN ammo",
        "STARSNCI3 ammo",
        "手枪弹夹 &8(&f12.7mm&8)", // 50_GS (DesertEagle)
        "MLRS6 ammo",
        "M60E4 ammo",
        "DRAGUNOV ammo",
        "SHULKERSNIPER ammo",
        "MW ammoBAG",
        "AMA40MM ammo",
        "小型核弹弹头", // Fatman
        "GAU30MMHE ammo",
        "DEVOTIONX55 ammo",
        "KCASLUGGER ammo",
        "12GHIGHEXPLOSIVE ammo",
        "霰弹枪子弹 &8(&f12 Gauge&8)", // Origin_12, R9_0
        "M4A1 弹夹",
        "M249 ammo",
        "格洛克弹夹",
        "HONEYBADGER ammo",
        "RPG-7 火箭", // RPG_7
        "12GFLECHETTE ammo",
        "L96 ammo",
        "PREDATOR37MMSR ammo",
        "榴弹",
        "M21 ammo",
        "PAW20 ammo",
        "12GPOISONEDFLECHETTE ammo",
        "榴弹 &8(&c燃烧&8)",
        "榴弹 &8(&a弹跳&8)",
        "GALIL ammo",
        "RPK ammo",
        "AU40MMHE ammo",
        "HCAR ammo",
        "KCASMART50 ammo",
        "APCRRIFLE ammo",
        "GAU20MM ammo",
        "W1200INCENDIARY ammo",
        "USPPOISON ammo",
        "ROCKETPOD68MM ammo",
        "毛瑟步枪子弹 &8(&f7.92mm&8)", // for Kar98k, can be used to craft 毛瑟步枪弹药盒 &8(&f7.92mm&8)
        "PANZERFAUST3 ammo",
        "MINIGUN ammoPORTABLE",
        "BASICSALVO ammo",
        "COLDWARE2 ammo",
        "榴弹 &8(&d毒气&8)",
        "AU40MM ammo",
        "RPD ammo",
        "G36 ammo",
        "Z45SENTINEL ammo",
        "AK74 ammo",
        "ADVANCEDSALVO ammo",
        "KCASMARTPISTOL ammo",
        "A91 ammo",
        "SPLITTERCANNON ammo",
        "PREDATOR37MM ammo",
        "PREDATOR37MMLR ammo",
        "SMG100 ammo",
        "榴弹 &8(&f闪光&8)",
        "VOLTV3 ammo",
        "JURY ammo",
        "STARSBURNINGRUBBER ammo",
        "GAU20MMHVLE ammo",
        "毛瑟步枪弹药盒 &8(&f7.92mm&8)", // MG34
        "KCASLUGGERKINETIC ammo",
        "USP ammo",
        "COLT45 ammo",
        "M9 ammo",
        "Z16SPLICERRIFLE ammo",
        "MASTIFF1218 ammo",
        "APPISTOL ammo",
        "Z15SPLICER ammo"
    )

}